### ISSUE TITLE
[Bug] Fail to resync after 1.8.0b3 Settings-Advanced-Resync

### ISSUE THREAD

**Issue by blupino** [Chia-Network/chia-blockchain-gui#1626]
### What happened?

I did testing on new feature "Settings-Advanced-Resync". After the client window exit, I restart the client again and after sometime it never complete the sync. The log included below.

This issue has been spotted since 1.7.0, and the remedy is to delete the wallet db and let the client rebuild db again.

### Version

1.8.0b3

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 551, in set_sync_mode
  File "chia/wallet/wallet_node.py", line 1185, in long_sync_from_untrusted
  File "chia/wallet/wallet_node.py", line 754, in long_sync
  File "chia/wallet/util/wallet_sync_utils.py", line 78, in subscribe_to_phs
ValueError: None response from peer 127.0.0.1 for register_interest_in_puzzle_hash
2023-03-19T18:41:19.036 wallet chia.wallet.wallet_node    : INFO     It took 0.6837668418884277 time to validate the weight proof
2023-03-19T18:41:19.094 wallet chia.wallet.wallet_state_manager: INFO     set_sync_mode syncing - range: 0-3400484
2023-03-19T18:41:19.094 wallet chia.wallet.wallet_node    : INFO     Starting sync trusted: False to peer 127.0.0.1
2023-03-19T18:41:19.094 wallet chia.wallet.wallet_node    : INFO     perform_atomic_rollback to 0
2023-03-19T18:41:20.403 wallet wallet                     : INFO     Reconnecting to peer PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=8444)
2023-03-19T18:41:20.509 wallet wallet_server              : INFO     Connected with full_node PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=8444)
2023-03-19T18:41:20.510 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145
2023-03-19T18:41:20.515 wallet chia.wallet.wallet_state_manager: ERROR    set_sync_mode failed - range: 0-3400484, seconds: 1.4407002925872803
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 551, in set_sync_mode
  File "chia/wallet/wallet_node.py", line 1185, in long_sync_from_untrusted
  File "chia/wallet/wallet_node.py", line 754, in long_sync
  File "chia/wallet/util/wallet_sync_utils.py", line 78, in subscribe_to_phs
ValueError: None response from peer 127.0.0.1 for register_interest_in_puzzle_hash
2023-03-19T18:41:22.511 wallet chia.wallet.wallet_node    : INFO     It took 0.671501874923706 time to validate the weight proof
2023-03-19T18:41:22.566 wallet chia.wallet.wallet_state_manager: INFO     set_sync_mode syncing - range: 0-3400484
2023-03-19T18:41:22.567 wallet chia.wallet.wallet_node    : INFO     Starting sync trusted: False to peer 127.0.0.1
2023-03-19T18:41:22.567 wallet chia.wallet.wallet_node    : INFO     perform_atomic_rollback to 0
2023-03-19T18:41:24.101 wallet wallet                     : INFO     Reconnecting to peer PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=8444)
2023-03-19T18:41:24.206 wallet wallet_server              : INFO     Connected with full_node PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=8444)
2023-03-19T18:41:24.206 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145
2023-03-19T18:41:24.212 wallet chia.wallet.wallet_state_manager: ERROR    set_sync_mode failed - range: 0-3400484, seconds: 1.66288161277771
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 551, in set_sync_mode
  File "chia/wallet/wallet_node.py", line 1185, in long_sync_from_untrusted
  File "chia/wallet/wallet_node.py", line 754, in long_sync
  File "chia/wallet/util/wallet_sync_utils.py", line 78, in subscribe_to_phs
ValueError: None response from peer 127.0.0.1 for register_interest_in_puzzle_hash
2023-03-19T18:41:25.871 wallet chia.wallet.wallet_node    : INFO     It took 0.6732425689697266 time to validate the weight proof
2023-03-19T18:41:25.926 wallet chia.wallet.wallet_state_manager: INFO     set_sync_mode syncing - range: 0-3400484
2023-03-19T18:41:25.926 wallet chia.wallet.wallet_node    : INFO     Starting sync trusted: False to peer 127.0.0.1
2023-03-19T18:41:25.926 wallet chia.wallet.wallet_node    : INFO     perform_atomic_rollback to 0
2023-03-19T18:41:27.450 wallet wallet                     : INFO     Reconnecting to peer PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=8444)
2023-03-19T18:41:27.616 wallet wallet_server              : INFO     Connected with full_node PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=8444)
2023-03-19T18:41:27.616 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145
2023-03-19T18:41:27.621 wallet chia.wallet.wallet_state_manager: ERROR    set_sync_mode failed - range: 0-3400484, seconds: 1.7116961479187012
```

**Comment by trepca** [comment]
@blupino thanks, are you connecting to your local full node? Did you try restarting the wallet again when this occurred? Did you have any other error messages before this error?

**Comment by blupino** [comment]
yes to local full node. I think so, I have spotted this issue few times I remember I restart the node and the issue still happen with 1.7.1rc2

This is for 1.7.1rc2, I think this is the point before it start keep closing the connection

6d5af819e7c7c848ce6b01c90a7d465d1b021b9c044991d4e69ae9c089d2bb1 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.226 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 760fc1af5d632a5fe8a9e458d59b593556972306df896648416c50217c2bb427 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.226 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: a24ee29b334e42f8afb097f0984034844b5dd6454f3d2034fa5e3d3f07f0308f not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.226 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 1bec64b37d30d0c4f4495f908162dfa70880fd86a85b13f0b851aed5ddcd57da not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.226 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 115f3016e0868ef721943a285f221043a665f9acdf680037639645c2d5f47195 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.226 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 07fecb22b4c777243c2f23aa920ed0117507e3124e3f566f0587d371658de5db not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.227 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 31eea6a11b97254d35722d0dd693b2ca0fbb1b0b149e0d9aafe90f4144e7d756 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.227 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: a5265b060fdf8386e8b13e5c907e542a43cb16c183a015efbe611c48c0c7dec2 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.227 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 8f1ec73715c1838996c08691a498e6fcdd64636f8489d322fb1c403edc79c0cb not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.227 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 24223b3594a3380ec55e3b81121a0a15807f731e6dd54a861b0a6b3eb202ddc9 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.227 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 050c36c61b50b2da2426fb8cc887304042b2832e9d1e9f04fb2973ecfa3bb7f1 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.227 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 65e964bae8fcbf4b85e99dd589177053f6e3038a8cb87c6788bb07aa1d600105 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.227 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: b03aa11db48d8a7ec4f33a5aaa791ea037e9006adc483cc0f622097c4b34bb6f not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.227 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: a1dc27502b7ced7f3bbc38321ea6dd1206c755bf93879abeb23d802d645a8d4a not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.227 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: c203d198e63b8d8af30b2863013f909fd558b0ed1451e87871e5f978e24c7334 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.228 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: b65c81320b76c57b1c96ab1ccb4dab086a4407ab637b02c1bbd72e1e23f99410 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.228 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: ed9204df6d216c0ba7feec1bb531d6b6c08f4899ed037944603253dae44eac50 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.228 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 54c91676b14d0da72f199ccd1643b2430fc1826d5b819d957ccfb77ba6c1e7b0 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.228 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: adaf2d7d13c59fa35e9a574cb6cb1603a5ad1027229bc4f118083b23cf71fe01 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.228 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 8ae9ece937fb4810b104791887de4a4b35f626ab9dc9f146d4a9facff29ae916 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.228 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 3328b4778d2a82615918dbc2cfe3a322615adb0194a2d11178f5ff78780f2c9c not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.228 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 5bc98776b1e425755061695968343af65e0c0316f61b5b0efbbe19d3bbf8938a not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.228 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: b3ff783fab90b8ecf328e96ceff170e95e779bce8316e69a52f5bcb2793718bb not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.229 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: e50ffa34d9258b96faba9f21bf26c2a076406d65d961f61b0ec24426b3501806 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.229 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 9267b649d9723e9d262cc10bb9d4c144fe61384f7e65b5b6b52b636388f25880 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.229 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 08a4ac256162354008722c89fc5bc1c4f7d4e09f8c4345bfa6644fc0d794b7b4 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.229 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 06c4774d59cfbdb2ababc82cf2d87e3cb26f60dc3568528063f6077a722f65fa not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.229 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 8d5c19ff7babc851d6c1c9b6ed6bf063e9e86aa0f4c5263165e263d8957ede34 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.229 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: f29b292b46031a804ce2158c0bd48e73ceda8c57f444f79653fc0a17a087165b not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.229 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: d4f3226ed11a90159cc7876178cc96edde04b3348df5d02e29541d3c26274210 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.229 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 815106f7f646b977078b7146ba6de02b70ab73128cbb47855ed481d635f06a82 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.230 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 8da3576c262090cbdf6a299211d492e81f340c336fc4fd37ec051db0544fcf85 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.230 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: f773b75cb450b0d7cd37c49a9a45deeefdbed2c119e2336b69648892b7d804dd not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.230 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 61b0878a9c295a55dad4e8a349a4bffef7040e23681a1fecf273747bfdee39e9 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:39.496 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-1/ 1)
2023-03-21T23:59:39.873 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-1/ 1)
2023-03-21T23:59:41.078 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 6e4bd9d34d41a80e3f275d39733488147c6441ad791fbc23486567a61836306c not in mempool. (peer, included, error) list: []
2023-03-21T23:59:41.078 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: ee4d896c647060c91a271fcd5a9d4fa5cfa707a57128faf400acda134043c740 not in mempool. (peer, included, error) list: []
2023-03-21T23:59:41.078 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 05134b11d66f7ca6f6ffc64902d7f50968fdca8891a40f718a716f3a4b8cc8ac not in mempool. (peer, included, error) list: []
2023-03-21T23:59:41.078 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: d056a45f12adce8e5f5a76e926df4c07b57ad5b41692205739f4706b76c243d2 not in mempool. (peer, included, error) list: []
2023-03-21T23:59:41.078 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: f513d0910eff371d5a633f7800552d673e08b11f9c4075023daf2c4b450c0244 not in mempool. (peer, included, error) list: []
2023-03-21T23:59:41.079 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 9ddc74ed8fcfb7110e19400a35121c2384a442a3e198dffd753f6917e0cfad6d not in mempool. (peer, included, error) list: []
2023-03-21T23:59:41.079 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 7c6a6caed13005b9043c9236c7394eed4c3fcfcca0090e8310d4f5c242928d39 not in mempool. (peer, included, error) list: []
2023-03-21T23:59:41.079 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 7c0eb603cccf196199471f9fa1e333784876618c9d1885ef3a4c4750bea30245 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.079 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 5c005c934b52a3fc24b054d862745b74bd298cb9c56af21e47f2f6f3019b3ffb not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.079 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 10fd25cc205f0a9347c134b5b539bd52b12f1c6eb78e56e67625a9721eb4b0d8 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.079 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 888825b4a6adf0927c7fffd77febc663a724a0fd9b9ff32b0812082a32a4895a not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.079 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 07e5fedd508d22a0fc569d101b77446a651fb3406d41f179e9e88ab0dcda8e52 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.079 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: eb3aa4b823d0efcf9d3d1f0ea7b23c79a083b04b270181c851617906796800c3 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.080 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: ce128d0933c31c9ce6e73496e75f25ba4d9d0cfc74d676d1685cde36f20e2757 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.080 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 96ba70c1b1cf0781d0c9ec7cea5a19ea01c36753807150f1c410a71a108ca093 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.080 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 6f7660847a61e7feb06a2c4741f84c3b02ed2b18520cf7c52699fed538f697a0 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.080 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 573b5e539a75922c478fac5169f5c2e627684a10d0efeeccf27c6e4dcb36527a not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.080 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: cf584503d4ff899d3e6ba792237fe6d83951e16e6326648c319e44594b39822b not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.080 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: b1b9b6fb1f48dbcd79a46788b3e291634ad0970d84805d3c976e95ed547e7e98 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.080 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 113e0578d7989d747fd02a3836281013cd1310cdb3c0375983edc8cbffb6a3b5 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.080 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: ad0e026cb070fa66648944fa506478c1572bdcfd563f4882d89d82d15475e38c not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.081 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 17f65ee11f9d17224a9d04d97402f009887f605e9c3adec744043d3778a83e3d not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.081 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 0ac98019e3a9012d272c318619343ea209234af00db680971bacc9d7f1ae6ddc not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.081 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 99ab94f43b0950dc30b680472297f03e6d93816adf08640840e08a4a28c94f4e not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.081 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 1468c5b35df371675050b5c1061c5a788980f07e9a531011ae9142ce937b3611 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.081 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 5eede64f36c5675dfc534b43ba4a34332af9dc1df4b567b5e077b2d850908aa5 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.081 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 022552d3f9df1a5acdd0204269f0eafa253ac66b0f719ac3460558d2216ee399 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.081 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: f9f8edd65daf51ec4ecb31176d920bbcc962f6eedf5fd2a583ee3b9520f1d926 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.081 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 5adb08d71573552c9ab3f7154ae4c80aeed3419fc8113c86098b294b22941d12 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.081 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 1813f3d4dc8a84267994d5b3b4bd0479900f56864aeb8caa7f639d50f34e4189 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.082 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 1af6a6c6426e156325acd44280a1a44fd097a2bd987e754930eaa1ccd408bec4 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.082 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 749f332dc63d4ca9eabed0afbf4ae3be318019abc36a2d14db536769dc9fcec0 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.082 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 7a5413392b01255cc7fbe482f930acad074c581e38b118310f38844212534310 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.082 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 34010b4f62578ec9b111c707bc447d0cee612a88e4dc3c3de1ecf3509d5ea8f7 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.082 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 899eb0f135aec49f2f17082b4ef7bcd122604853e44892b131350b1206ed6ae5 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.082 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 84d56167fde59e85e158c5c88a6318a3144ebab7534ae2a9467176093ccb484b not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.082 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 46d5af819e7c7c848ce6b01c90a7d465d1b021b9c044991d4e69ae9c089d2bb1 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.083 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 760fc1af5d632a5fe8a9e458d59b593556972306df896648416c50217c2bb427 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.083 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: a24ee29b334e42f8afb097f0984034844b5dd6454f3d2034fa5e3d3f07f0308f not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.083 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 1bec64b37d30d0c4f4495f908162dfa70880fd86a85b13f0b851aed5ddcd57da not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.083 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 115f3016e0868ef721943a285f221043a665f9acdf680037639645c2d5f47195 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.083 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 07fecb22b4c777243c2f23aa920ed0117507e3124e3f566f0587d371658de5db not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.083 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 31eea6a11b97254d35722d0dd693b2ca0fbb1b0b149e0d9aafe90f4144e7d756 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.083 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: a5265b060fdf8386e8b13e5c907e542a43cb16c183a015efbe611c48c0c7dec2 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.083 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 8f1ec73715c1838996c08691a498e6fcdd64636f8489d322fb1c403edc79c0cb not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.084 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 24223b3594a3380ec55e3b81121a0a15807f731e6dd54a861b0a6b3eb202ddc9 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.084 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 050c36c61b50b2da2426fb8cc887304042b2832e9d1e9f04fb2973ecfa3bb7f1 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.084 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 65e964bae8fcbf4b85e99dd589177053f6e3038a8cb87c6788bb07aa1d600105 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.084 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: b03aa11db48d8a7ec4f33a5aaa791ea037e9006adc483cc0f622097c4b34bb6f not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.084 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: a1dc27502b7ced7f3bbc38321ea6dd1206c755bf93879abeb23d802d645a8d4a not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.084 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: c203d198e63b8d8af30b2863013f909fd558b0ed1451e87871e5f978e24c7334 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.084 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: b65c81320b76c57b1c96ab1ccb4dab086a4407ab637b02c1bbd72e1e23f99410 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.084 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: ed9204df6d216c0ba7feec1bb531d6b6c08f4899ed037944603253dae44eac50 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.085 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 54c91676b14d0da72f199ccd1643b2430fc1826d5b819d957ccfb77ba6c1e7b0 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.085 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: adaf2d7d13c59fa35e9a574cb6cb1603a5ad1027229bc4f118083b23cf71fe01 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.085 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 8ae9ece937fb4810b104791887de4a4b35f626ab9dc9f146d4a9facff29ae916 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.085 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 3328b4778d2a82615918dbc2cfe3a322615adb0194a2d11178f5ff78780f2c9c not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.085 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 5bc98776b1e425755061695968343af65e0c0316f61b5b0efbbe19d3bbf8938a not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.085 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: b3ff783fab90b8ecf328e96ceff170e95e779bce8316e69a52f5bcb2793718bb not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.085 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: e50ffa34d9258b96faba9f21bf26c2a076406d65d961f61b0ec24426b3501806 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.085 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 9267b649d9723e9d262cc10bb9d4c144fe61384f7e65b5b6b52b636388f25880 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.085 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 08a4ac256162354008722c89fc5bc1c4f7d4e09f8c4345bfa6644fc0d794b7b4 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.086 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 06c4774d59cfbdb2ababc82cf2d87e3cb26f60dc3568528063f6077a722f65fa not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.086 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 8d5c19ff7babc851d6c1c9b6ed6bf063e9e86aa0f4c5263165e263d8957ede34 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.086 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: f29b292b46031a804ce2158c0bd48e73ceda8c57f444f79653fc0a17a087165b not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.086 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: d4f3226ed11a90159cc7876178cc96edde04b3348df5d02e29541d3c26274210 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.086 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 815106f7f646b977078b7146ba6de02b70ab73128cbb47855ed481d635f06a82 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.086 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 8da3576c262090cbdf6a299211d492e81f340c336fc4fd37ec051db0544fcf85 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.086 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: f773b75cb450b0d7cd37c49a9a45deeefdbed2c119e2336b69648892b7d804dd not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.087 wallet chia.wallet.wallet         : WARNING  TransactionRecord SpendBundle ID: 61b0878a9c295a55dad4e8a349a4bffef7040e23681a1fecf273747bfdee39e9 not in mempool. (peer, included, error) list: [('fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145', 3, 'DOUBLE_SPEND')]
2023-03-21T23:59:41.359 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-1/ 1)
2023-03-21T23:59:41.740 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-1/ 1)
2023-03-21T23:59:42.271 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.271 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.271 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.271 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.271 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.271 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.272 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.272 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.272 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.272 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.272 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.272 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.272 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.272 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.273 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.273 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.273 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.273 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.273 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.273 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.273 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.273 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.274 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.274 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.274 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.274 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.274 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.274 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.274 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.274 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.275 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.275 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.275 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.275 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.275 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.275 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.275 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.275 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.276 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.276 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.276 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.276 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.276 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.276 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.276 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.276 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.277 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.277 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.277 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.277 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.277 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.277 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.277 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.278 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.278 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.278 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.278 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.278 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.278 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.278 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.278 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.279 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.279 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.279 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.279 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.279 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.279 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.279 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:42.279 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-03-21T23:59:42.279 wallet wallet_server              : WARNING  Trying to ban localhost for 120, but will not ban
2023-03-21T23:59:43.840 wallet chia.full_node.weight_proof: INFO     validating 8882 sub epochs
2023-03-21T23:59:43.845 wallet chia.full_node.weight_proof: INFO     validate weight proof peak height 3410751
2023-03-21T23:59:44.904 wallet wallet                     : INFO     Reconnecting to peer PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=8444)
2023-03-21T23:59:44.910 wallet wallet_server              : INFO     Connected with full_node PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=8444)
2023-03-21T23:59:44.911 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: fbe3b5cebeabceac3a3722b0805e6840a4f5936c7ed5fd5296e323ed155bc145

**Comment by trepca** [comment]
@blupino thanks, we have fixed a few issues relating to failed transactions in latest RC if you can try it out: https://github.com/Chia-Network/chia-blockchain/releases/tag/1.7.1-rc3

**Comment by blupino** [comment]
This is debug log when issue happen on 1.7.1-rc2, I think it start at debug.log.1 offset 2023-03-23T00:22:27.261

going to try the rc3

[cannot_sync_log.tgz](https://github.com/Chia-Network/chia-blockchain-gui/files/11042512/cannot_sync_log.tgz)

**Comment by blupino** [comment]
1.7.1-rc3 still have this issue, unfortunately I don't have the log now because the important part has been overwritten

**Comment by paninaro** [comment]
Closing due to inactivity
