### ISSUE TITLE
[BUG] bad translation in spanish version

### ISSUE THREAD

**Issue by fga352** [Chia-Network/chia-blockchain-gui#348]
Describe the bug
translation of farming is "cultivando" not "joseando". Joseando doesn't exist in RAE https://www.rae.es/

To Reproduce

Go to 'Language'
Click on 'Spanish'
Go to "Parcelas" or "Granja"
See error
Expected behavior
I expect "Cultivando". Joseando doesn't have meaning in spanish language. Maybe in latam spanish but not in spanish.

This error is in 1.1.3 version. In 1.1.2 the word is "cultivando".

**Comment by seeden** [comment]
This issue was already fixed.

**Comment by angvp** [comment]
But is not fixed, see the title it says Joseando.

![joseando](https://user-images.githubusercontent.com/13283/117895643-ced28200-b28c-11eb-8dff-c5a96408160d.png)

**Comment by egmsystems** [comment]
correct, in the file main.js line 28750 Farming: "Joseando",
in this file shoeld be change Joseando with Cultivando

**Comment by angvp** [comment]
I guess this is in a issue with the tool for i18n and the current project, probably some sort of cache or something @seeden please have a look, as we mentioned earlier this issue is still present and shouldn't be closed.

**Comment by seeden** [comment]
Hi.
It was already fixed and merged a few days ago. Version 1.1.5 is using the old version of the GUI.
There is no "joseando" in the es-ES anymore https://github.com/Chia-Network/chia-blockchain-gui/blob/main/src/locales/es-ES/messages.po

**Comment by angvp** [comment]
How do we get the new version, as I'm running the code from electron (cloning it separately) and it also says Joseando tho, maybe I need to do a different step?

**Comment by fga352** [comment]
+1

**Comment by alexlv4** [comment]
Joseando ando y mi granja cultivando....
