### ISSUE TITLE
Infinite Loading screen

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-blockchain-gui#629]
Uncaught (in promise) Error: Error invoking remote method 'getConfig': TypeError: l is not a function
    at EventEmitter.i.invoke (electron/js2c/renderer_init.js:65)

I get an infinite spinner "Loading configuration", on chia-blockchain main, and also when I change to the NEXT branch.

**Comment by mariano54** [comment]
Still not working.
I have tried deleting the .chia/testnet10 folder, and also tried initializing it first in the command line, always same error.

However when starting chia from the command line it works fine.

**Comment by mariano54** [comment]
> Maybe these are the root cause. https://github.com/Chia-Network/chia-blockchain-gui/blob/NEXT/packages/gui/src/components/app/AppProviders.tsx#L12
> 
> https://github.com/Chia-Network/chia-blockchain-gui/blob/NEXT/packages/gui/src/util/config.js#L13
> 
> Infinite `while(true)` loop waiting to load config. One possibility is you need to run `chia init` or create valid chia folder manually

Thank you i will check those files

**Comment by mariano54** [comment]
This is what I get when running with `chia run dev:gui`

```
Error invoking remote method 'getConfig': TypeError: sleep is not a function
Call Stack
 EventEmitter.i.invoke
  js2c/renderer_init.js:65:526
 async init
  main.js:48097:20
```

**Comment by mariano54** [comment]
```
@chia/gui: [1] Error occurred in handler for 'getConfig': TypeError: sleep is not a function
@chia/gui: [1]     at Object.loadConfig (/home/mariano54/Chia/chia-blockchain/chia-blockchain-gui/packages/gui/build/electron/main.js:62570:13)
@chia/gui: [1]     at /home/mariano54/Chia/chia-blockchain/chia-blockchain-gui/packages/gui/build/electron/main.js:130393:132
@chia/gui: [1]     at electron/js2c/browser_init.js:197:579
@chia/gui: [1]     at Object.<anonymous> (electron/js2c/browser_init.js:161:10272)
@chia/gui: [1]     at Object.emit (events.js:376:20)
@chia/gui: [1] Waiting for configuration file
```

**Comment by mariano54** [comment]
Electron 14.2.3
node 14.17.0

**Comment by ChiaMineJP** [comment]
` Error occurred in handler for 'getConfig': TypeError: sleep is not a function`
This is really strange. According to the error message, root cause might be https://github.com/Chia-Network/chia-blockchain-gui/blob/NEXT/packages/gui/src/util/config.js#L54

If you can edit javascript source, try to replace the line above. (Replace `sleep` with something working)
The path to the exception handler is not only from error loading configration file from `CHIA_ROOT` but also missing certification files as well.
https://github.com/Chia-Network/chia-blockchain-gui/blob/NEXT/packages/gui/src/util/config.js#L48...L49

Checking whether ssl certs exist at the expected location should be a help to your problem.

**Comment by seeden** [comment]
It looks like a rebase issue. I will fix it in few minutes

**Comment by seeden** [comment]
Fix pushed to NEXT branch

**Comment by mariano54** [comment]
It's still not working, I'm getting:
@chia/gui: [1] Waiting for configuration file

although the previous error is gone

**Comment by emlowe** [comment]
Don't we need node 16 and npm 7? @ChiaMineJP Don't you have some install script fixes in a branch?

**Comment by ChiaMineJP** [comment]
Yes, we need `npm>=7` for the latest GUI branch.
https://github.com/Chia-Network/chia-blockchain/pull/9921/

Try the below. My new `install-gui.sh` automatically upgrade nodejs/npm if its version is too old.
```shell
cd <path-to-chia-blockchain>
git checkout use_more_n # Resolve / reset if there are conflicts.
sh install.sh
. ./activate
sh install-gui.sh
sh start-gui.sh
```

**Comment by paninaro** [comment]
I was able to narrow this down and get things working. I believe there are two unrelated issues that are causing this, but the main issue with the GUI is that the call to `window.ipcRenderer.invoke('getConfig');` in `AppProviders.tsx` isn't await-upon. So if config.yaml isn't in place when the GUI attempts to load the config, the `config` variable will be an unresolved Promise object. Changing the line to the following got me past that issue:

`const config = await window.ipcRenderer.invoke('getConfig');`

The second issue that I need to dig into more is that the daemon fails to launch (at least in my testing). I captured the following traceback:

`
[1] stderr: Traceback (most recent call last):
[1]   File "/Users/jeffc/src/macos/chia-blockchain/chia-blockchain-gui/packages/gui/../../../chia/daemon/server.py", line 1472, in <module>
[1]     main(sys.argv[1:])
[1]   File "/Users/jeffc/src/macos/chia-blockchain/chia-blockchain-gui/packages/gui/../../../chia/daemon/server.py", line 1468, in main
[1]     return run_daemon(DEFAULT_ROOT_PATH, wait_for_unlock)
[1]   File "/Users/jeffc/src/macos/chia-blockchain/chia-blockchain-gui/packages/gui/../../../chia/daemon/server.py", line 1459, in run_daemon
[1] stderr:     result = asyncio.get_event_loop().run_until_complete(async_run_daemon(root_path, wait_for_unlock))
[1]   File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
[1] stderr:     return future.result()
[1]   File "/Users/jeffc/src/macos/chia-blockchain/chia-blockchain-gui/packages/gui/../../../chia/daemon/server.py", line 1420, in async_run_daemon
[1] stderr:     chia_init(root_path, should_check_keys=(not wait_for_unlock))
[1]   File "/Users/jeffc/src/macos/chia-blockchain/chia/cmds/init_funcs.py", line 442, in chia_init
[1] stderr:     connection.execute("CREATE TABLE database_version(version int)")
[1] sqlite3.OperationalError: table database_version already exists
`

Updating `init_funcs.py` such that `CREATE TABLE database_version(version int)` -> `CREATE TABLE IF NOT EXISTS database_version(version int)` cleared up the daemon launching issue.

**Comment by paninaro** [comment]
It looks like the DB issue was a side-effect of my method for repro'ing the GUI issue. It doesn't seem to be a problem in normal operation. I was pausing the app during startup and manually moving config.yaml aside, which then exposed the DB issue.

**Comment by paninaro** [comment]
Should be fixed with commit [26646cbba6c4e04d390e1830e430252e81a33f87](https://github.com/Chia-Network/chia-blockchain-gui/commit/26646cbba6c4e04d390e1830e430252e81a33f87)
